#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Jun  6 01:39:04 2025
#

import wx
from getCompetitionNames import getCompetitionNamesNumber
from clearTables import clear
from removeParticipant import removeParticipant
from removeResult import removeResult
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade 

"""Класс, отвечающий за страницу удаления данных
ОПИСАНИЕ:
    Класс создаёт все виджеты на странице, отвечает за подтягивание данных с базы данных,
    Также отвечает за вывод ошибок в случае неправильной работы с приложением
"""
class Deleter(wx.Panel):
    def __init__(self, parent):
        
        # вызов конструктора наследника с указанием того-же родителя, что и у класса Participants_viewver
        super(Deleter, self).__init__(parent) 
        
        # Вспомогательные переменные
        self.number = 0
        
        # Задание размеров, цвета фона, цвета шрифта, шрифта
        self.SetSize((600, 550))
        self.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        self.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_3DDKSHADOW))
        self.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        # Создание разметки верхнего уровня
        grid_sizer_1 = wx.FlexGridSizer(8, 1, 30, 0)
        
        # Создание надписи Удаление одной записи
        label_4 = wx.StaticText(self, wx.ID_ANY, u"Удаление одной записи", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_4.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_4, 1, wx.ALIGN_CENTER)
        
        
        # Создание разметки для удаления по номеру
        grid_sizer_2 = wx.FlexGridSizer(2, 1, 10, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.ALIGN_CENTER, 30)

        # Создание надписи Номер участника
        label_1 = wx.StaticText(self, wx.ID_ANY, u"Номер участника", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER | wx.TOP, 15)

        # Создание разметки для поиска участника по номеру
        grid_sizer_5 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_5, 1, 0, 0)

        # Текстовое поле для ввода номера участника 
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.text_ctrl_1.SetMinSize((300, 33))
        grid_sizer_5.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.RIGHT | wx.TOP, 5)

        # Кнопка для поиска участника
        self.button_3 = wx.Button(self, wx.ID_ANY, u"Искать")
        self.button_3.SetMinSize((150, 50))
        self.button_3.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_3.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        grid_sizer_5.Add(self.button_3, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        
        # Создание разметки для выбора соревнования и удаления участника
        grid_sizer_4 = wx.FlexGridSizer(3, 1, 10, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.ALIGN_CENTER, 30)

        # Создание текстового поля Соревнования
        label_3 = wx.StaticText(self, wx.ID_ANY, u"Соревнования")
        grid_sizer_4.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        # Создание поля для выбора соревнования из которого нужно удалить данные
        self.choice_4 = wx.Choice(self, wx.ID_ANY, choices=[])
        self.choice_4.SetMinSize((458, 33))
        grid_sizer_4.Add(self.choice_4, 0, wx.BOTTOM, 30)

        # Кнопка для удаления определённого результата соревнования
        self.button_5 = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.button_5.SetMinSize((145, 50))
        self.button_5.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_5.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        grid_sizer_4.Add(self.button_5, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        
        # Текстовое поле Удаление участника по номеру
        label_5 = wx.StaticText(self, wx.ID_ANY, u"Удаление участника по номеру", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_5.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_5, 1, wx.ALIGN_CENTER)
        
        # Создание разметки для удаления участника по номеру
        grid_sizer_6 = wx.FlexGridSizer(3, 1, 10, 0)
        grid_sizer_1.Add(grid_sizer_6, 0, wx.ALIGN_CENTER)
        
        # Текстовое поле Номер участника
        label_2 = wx.StaticText(self, wx.ID_ANY, u"Номер участника", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_6.Add(label_2, 0, wx.ALIGN_CENTER | wx.TOP, 15)
        
        # Создание разметки для кнопки удалить и ввода номера
        grid_sizer_7 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_6.Add(grid_sizer_7, 1, 0, 0)    
        
        # Поле для ввода номера
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.text_ctrl_2.SetMinSize((300, 33))
        grid_sizer_7.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.RIGHT | wx.TOP, 5)

        # Кнопка удалить
        self.button_2 = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.button_2.SetMinSize((150, 50))
        self.button_2.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_2.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        grid_sizer_7.Add(self.button_2, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        
        # надпись Удаление всех записей о соревновании
        label_6 = wx.StaticText(self, wx.ID_ANY, u"Удаление всех записей о соревновании", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_6, 1, wx.ALIGN_CENTER)        
        
        # Кнопка для удаоения данных
        self.button_1 = wx.Button(self, wx.ID_ANY, "Удалить все записи")
        self.button_1.SetMinSize((250, 50))
        self.button_1.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_1.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        grid_sizer_1.Add(self.button_1, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        
        # Привязка событий
        self.button_1.Bind(wx.EVT_BUTTON, self.del_all )
        self.button_2.Bind(wx.EVT_BUTTON, self.delete_button_participant)
        self.button_3.Bind(wx.EVT_BUTTON, self.search_button_1)
        self.button_5.Bind(wx.EVT_BUTTON, self.delete_button_competition)

        self.SetSizer(grid_sizer_1)
        grid_sizer_1.AddGrowableCol(0)
        self.Layout()
        # end wxGlade
    
    # Функция для поиска участника в разделе удаление результата соревнования
    def search_button_1(self, event):
        
        try:
            # Попытка получить номер и преобразовать его в целое
            self.number = int(self.text_ctrl_1.GetValue().strip().replace(",", "."))
        except:
            wx.MessageBox("Введите численное значение в поле Номер участника", "Ошибка", wx.ICON_ERROR)
            return
        
        # Проеверка - существует ли участни с таким номером
        if (list(getCompetitionNamesNumber(self.number).keys()) == None):
            wx.MessageBox("Нет такого участника", "Информация", wx.ICON_INFORMATION)
            return
        
        # Получения списка соревнованй, доступных участнику
        self.choice_4.Set(list(getCompetitionNamesNumber(self.number).keys()))
        self.choice_4.SetSelection(0)
        
    # Функция для поиска участника в разделе удаление участника
    def delete_button_participant(self, event):
        try:
             # Попытка получить номер и преобразовать его в целое
            self.number = int(self.text_ctrl_2.GetValue().strip().replace(",", "."))
        except:
            wx.MessageBox("Введите численное значение в поле Номер участника", "Ошибка", wx.ICON_ERROR)
            return
        
        # Проеверка - существует ли участни с таким номером
        if (list(getCompetitionNamesNumber(self.number).keys()) == None):
            wx.MessageBox("Нет такого участника", "Информация", wx.ICON_INFORMATION)
            return
        
        # Удаление участника
        removeParticipant(self.number)
        wx.MessageBox("Информация удалена", "Успех", wx.ICON_INFORMATION)
        
        # Сброс введённых данных
        self.text_ctrl_1.SetValue("")
        self.text_ctrl_2.SetValue("")
        self.choice_4.Set([])
        self.number = 0
    
    # функция, вызываемая для удаления результатов соревнования
    def delete_button_competition(self, event):
        # Проврка - введен ли номер и выбрано ли соревнование
        if self.choice_4.GetStringSelection() == None or self.number == 0:
            wx.MessageBox("Не хватает данных", "Ошибка", wx.ICON_ERROR)
            return
        
        # Удаление результата
        removeResult(self.number, self.choice_4.GetStringSelection())
        
        # Сброс введённых данных
        self.text_ctrl_1.SetValue("")
        self.text_ctrl_2.SetValue("")
        self.choice_4.Set([])
        self.number = 0
    
    # Кнопка для удаления всех внесённых данных
    def del_all(self, event):
        # Сообщение с предупреждением
        dialog = wx.MessageDialog(self, """
                        Нажатие этой кнопки удаляет все записи об этом соревновании,
                        рекомендуем нажимать эту кнопку только в том случае,
                        если соревнование закончилось.
                        Вы уверены, что хотите удалить все данные ?
                        """, "ВНИМАНИЕ!", wx.YES_NO | wx.ICON_WARNING | wx.CANCEL)
        
        answer = dialog.ShowModal()
        dialog.Destroy()
        
        # Проверка ответа пользователя
        if answer == wx.ID_YES:
            # Удлаение данных
            clear()
            
        # Сброс данных
        self.number = 0