#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Jun  6 01:39:04 2025
#

import wx
from getCompetitionNames import getCompetitionNamesNumber
from clearTables import clear
from removeParticipant import removeParticipant
from removeResult import removeResult
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade 


class Deleter(wx.Panel):
    def __init__(self, parent):
        super(Deleter, self).__init__(parent) 
        self.number = 0
        # begin wxGlade: Deleter.__init__
        self.SetSize((600, 550))
        self.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        self.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_3DDKSHADOW))
        self.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        grid_sizer_1 = wx.FlexGridSizer(8, 1, 30, 0)
        label_4 = wx.StaticText(self, wx.ID_ANY, u"Удаление одной записи", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_4.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_4, 1, wx.ALIGN_CENTER)
        
        grid_sizer_2 = wx.FlexGridSizer(2, 1, 10, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.LEFT | wx.RIGHT, 30)

        label_1 = wx.StaticText(self, wx.ID_ANY, u"Номер участника", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_2.Add(label_1, 0, wx.ALIGN_CENTER | wx.TOP, 15)

        grid_sizer_5 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_5, 1, 0, 0)

        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.text_ctrl_1.SetMinSize((300, 33))
        grid_sizer_5.Add(self.text_ctrl_1, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.RIGHT | wx.TOP, 5)

        self.button_3 = wx.Button(self, wx.ID_ANY, u"Искать")
        self.button_3.SetMinSize((150, 50))
        self.button_3.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_3.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        grid_sizer_5.Add(self.button_3, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        
        
        grid_sizer_3 = wx.FlexGridSizer(2, 1, 10, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.LEFT | wx.RIGHT, 30)


        grid_sizer_4 = wx.FlexGridSizer(4, 1, 10, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.LEFT | wx.RIGHT, 30)

        label_3 = wx.StaticText(self, wx.ID_ANY, u"Соревнования")
        grid_sizer_4.Add(label_3, 0, wx.ALIGN_CENTER, 0)

        self.choice_4 = wx.Choice(self, wx.ID_ANY, choices=[])
        self.choice_4.SetMinSize((458, 33))
        grid_sizer_4.Add(self.choice_4, 0, wx.BOTTOM, 30)

        self.button_5 = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.button_5.SetMinSize((145, 50))
        self.button_5.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_5.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        
        grid_sizer_4.Add(self.button_5, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        
        
        label_5 = wx.StaticText(self, wx.ID_ANY, u"Удаление участника по номеру", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_5.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_5, 1, wx.ALIGN_CENTER)
        
        grid_sizer_6 = wx.FlexGridSizer(3, 1, 10, 0)
        grid_sizer_1.Add(grid_sizer_6)
        label_2 = wx.StaticText(self, wx.ID_ANY, u"Номер участника", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_6.Add(label_2, 0, wx.ALIGN_CENTER | wx.TOP, 15)
        grid_sizer_7 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_6.Add(grid_sizer_7, 1, 0, 0)        
        self.text_ctrl_2 = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER)
        self.text_ctrl_2.SetMinSize((300, 33))
        grid_sizer_7.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER | wx.BOTTOM | wx.RIGHT | wx.TOP, 5)

        self.button_2 = wx.Button(self, wx.ID_ANY, u"Удалить")
        self.button_2.SetMinSize((150, 50))
        self.button_2.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_2.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        grid_sizer_7.Add(self.button_2, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        
        label_6 = wx.StaticText(self, wx.ID_ANY, u"Удаление всех записей о соревновании", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_6.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_1.Add(label_6, 1, wx.ALIGN_CENTER)        
                
        self.button_1 = wx.Button(self, wx.ID_ANY, "Удалить все записи")
        self.button_1.SetMinSize((250, 50))
        self.button_1.SetBackgroundColour(wx.Colour(204, 50, 50))
        self.button_1.SetForegroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BTNHIGHLIGHT))
        grid_sizer_1.Add(self.button_1, 1, wx.ALIGN_CENTER | wx.ALL, 5)
        self.button_1.Bind(wx.EVT_BUTTON, self.del_all )
        self.button_2.Bind(wx.EVT_BUTTON, self.delete_button_participant)
        self.button_3.Bind(wx.EVT_BUTTON, self.search_button_1)
        self.button_5.Bind(wx.EVT_BUTTON, self.delete_button_competition)

        self.SetSizer(grid_sizer_1)

        self.Layout()
        # end wxGlade
    def search_button_1(self, event):
        
        try:
            self.number = int(self.text_ctrl_1.GetValue().strip().replace(",", "."))
        except:
            wx.MessageBox("Введите численное значение в поле Номер участника", "Ошибка", wx.ICON_ERROR)
            return
        if (list(getCompetitionNamesNumber(self.number).keys()) == None):
            wx.MessageBox("Нет такого участника", "Информация", wx.ICON_INFORMATION)
            return
        self.choice_4.Set(list(getCompetitionNamesNumber(self.number).keys()))
        self.choice_4.SetSelection(0)
        

        
        
    def delete_button_participant(self, event):
        try:
            self.number = int(self.text_ctrl_2.GetValue().strip().replace(",", "."))
        except:
            wx.MessageBox("Введите численное значение в поле Номер участника", "Ошибка", wx.ICON_ERROR)
            return
        if (list(getCompetitionNamesNumber(self.number).keys()) == None):
            wx.MessageBox("Нет такого участника", "Информация", wx.ICON_INFORMATION)
            return
        removeParticipant(self.number)
        wx.MessageBox("Информация удалена", "Успех", wx.ICON_INFORMATION)
        self.text_ctrl_1.SetValue("")
        self.text_ctrl_2.SetValue("")
        self.choice_4.Set([])
        self.number = 0
        
    def delete_button_competition(self, event):
        if self.choice_4.GetStringSelection() == None or self.number == 0:
            wx.MessageBox("Не хватает данных", "Ошибка", wx.ICON_ERROR)
            return
        removeResult(self.number, self.choice_4.GetStringSelection())
        self.text_ctrl_1.SetValue("")
        self.text_ctrl_2.SetValue("")
        self.choice_4.Set([])
        self.number = 0
        
    def del_all(self, event):
        dialog = wx.MessageDialog(self, """
                        Нажатие этой кнопки удаляет все записи об этом соревновании,
                        рекомендуем нажимать эту кнопку только в том случае,
                        если соревнование закончилось.
                        Вы уверены, что хотите удалить все данные ?
                        """, "ВНИМАНИЕ!", wx.YES_NO | wx.ICON_WARNING | wx.CANCEL)
        
        answer = dialog.ShowModal()
        dialog.Destroy()
        if answer == wx.ID_YES:
            clear()
        self.number = 0