#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Mon Jun  9 10:50:57 2025
#

import wx
from registration import Registration
from viewver import Viewer
from inputer import Inputer
from deleter import Deleter
from team_viewver import Team_viewer
from all_particepants_viewver import Participants_viewver
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

"""
    TODO:
        Сделать удаление по номеру 
        Сделать вывод по командам
"""

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1000, 900))
        self.SetTitle("Помощник ГТО")

        grid_sizer_1 = wx.FlexGridSizer(1, 1, 10, 10)

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style= wx.NB_TOP)
        grid_sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        
        self.notebook_1.AddPage(Viewer(self.notebook_1), u"Личный зачет")

        self.notebook_1.AddPage(Team_viewer(self.notebook_1), u"Командный зачет")
        
        self.notebook_1.AddPage(Participants_viewver(self.notebook_1), u"Участники")
        
        self.notebook_1.AddPage(Inputer(self.notebook_1), u"Ввод")

        self.notebook_1.AddPage(Registration(self.notebook_1), u"Регистрация")

        self.notebook_1.AddPage(Deleter(self.notebook_1), u"Удаление")

        self.SetSizer(grid_sizer_1)

        self.Layout()
        # end wxGlade

        
# end of class MainFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.frame.SetIcon(wx.Icon("GTO_ICON.png"))
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
