#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Mon Jun  9 10:50:57 2025
#

import wx
from registration import Registration
from viewver import Viewer
from inputer import Inputer
from clearTables import clear
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

"""
    TODO:
        Сделать удаление по номеру 
        Сделать вывод по командам
"""

class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1000, 900))
        self.SetTitle("Помошник_ГТО")

        grid_sizer_1 = wx.FlexGridSizer(1, 1, 10, 10)

        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=wx.NB_FIXEDWIDTH | wx.NB_TOP)
        grid_sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        
        self.notebook_1.AddPage(Viewer(self.notebook_1), u"Просмоторщик")

        self.notebook_1.AddPage(Inputer(self.notebook_1), u"Ввод")

        self.notebook_1.AddPage(Registration(self.notebook_1), u"Регистрация")

        # self.button_1 = wx.Button(self, wx.ID_ANY, "Удалить всё")
        # self.button_1.SetBackgroundColour(wx.RED)
        # self.button_1.SetForegroundColour(wx.WHITE)
        # self.button_1.Bind(wx.EVT_BUTTON, self.del_all )
        # grid_sizer_1.Add(self.button_1)
        self.SetSizer(grid_sizer_1)

        self.Layout()
        # end wxGlade
    # def del_all(self, event):
    #     dialog = wx.MessageDialog(self, """
    #                   Нажатие этой кнопки удаляет все записи об этом соревновании,
    #                   рекомендуем нажимать эту кнопку только в том случае,
    #                   если соревнование закончилось.
    #                   Вы уверены, что хотите удалить все данные ?
    #                   """, "ВНИМАНИЕ!", wx.YES_NO | wx.ICON_WARNING | wx.CANCEL)
    #     answer = dialog.ShowModal()
    #     dialog.Destroy()
    #     if answer == wx.ID_YES:
    #         clear()
        
# end of class MainFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
