#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Mon Jun  9 10:50:57 2025
#

import wx
from registration import Registration
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1000, 1000))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        grid_sizer_1 = wx.FlexGridSizer(2, 1, 10, 10)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY, style=wx.NB_FIXEDWIDTH | wx.NB_TOP)
        grid_sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        
        self.notebook_1.AddPage(self.notebook_1_pane_1, u"Просмоторщик")

        self.notebook_1_ = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.notebook_1_, u"Ввод")

        self.notebook_1_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(Registration(self.notebook_1), u"Регистрация")

        grid_sizer_1.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(grid_sizer_1)

        self.Layout()
        # end wxGlade

# end of class MainFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
